### ISSUE TITLE
システム化する範囲の決定

### ISSUE THREAD

**Issue by yoshioH** [dokurin/exhibition#19]
システム化する範囲を決めておかないと、画面モックを作っても意味ないよね。

**Comment by yoshioH** [comment]
システム化する範囲の草案を考える。

**Comment by ryutah** [comment]
ミニマムで実装してくのがいいんじゃないかなあ
とりあえず、実装を進めていかないと、設計とかだけで満足して終わる未来が見えてくるので、プロトライプをガンガン作りながらシステム化範囲を固めていくもがいいのかなって。

**Comment by yoshioH** [comment]
そうね。ミニマムだとこんな感じかな？
- 展示会画面（クリエイター一覧と作品閲覧ページ）
- 運営者の作品登録バッチ

**Comment by yoshioH** [comment]
- 展示会画面（クリエイター一覧と作品閲覧ページ）
- 運営者の作品登録バッチ
