### ISSUE TITLE
業務フローを作成する

### ISSUE THREAD

**Issue by yoshioH** [dokurin/exhibition#2]
UMLのアクティビティ図を作成する。

**Comment by second10** [comment]
[

](url)
[展示会.zip](https://github.com/dokurin/exhibition/files/5212327/default.zip)

**Comment by ryutah** [comment]
今更ながら、書いてくれた業務フローどの順番で読めばいいのかちょっと分かりづらいので索引つけるとかしたほうが良いかもと思った
