### ISSUE TITLE
Codeのディレクトリ構成を決める

### ISSUE THREAD

**Issue by yoshioH** [dokurin/exhibition#21]
とりあえずドキュメントを管理したい。

- doc
- src

で分ける。

**Comment by ryutah** [comment]
https://github.com/golang-standards/project-layout

とりあえず、僕がapiディレクトリ切ったのは↑これをベースにしてるからっすねー

**Comment by ryutah** [comment]
何をベースにするかって思想的な所も入ってくるし、言語によって標準的なディレクトリ構成は違ってくるので、ぼちぼち言語とかを決めないとって感じですかねー。

**Comment by yoshioH** [comment]
なるほどねー。
とりあえず、ドキュメントを格納できないのをどうにかしたい。

**Comment by ryutah** [comment]
ドキュメントはとりあえず `docs` 切るで良さそうかな？
まあ、本コードは置いておいてとりあえずのプロトタイプとかを `example` とかのフォルダ切って作ってってみたりします？？

**Comment by yoshioH** [comment]
そうね、
- docs
- example
でとりあえずきっておこう。

**Comment by yoshioH** [comment]
https://github.com/golang-standards/project-layout
ぽくディレクトリを切っておきます。
