### ISSUE TITLE
サーバの言語何を使うか決定する

### ISSUE THREAD

**Issue by ryutah** [dokurin/exhibition#23]
## Todo

- 伝助でも使ってアンケート取ってみる

refs #21

**Comment by ryutah** [comment]
伝助作った

https://densuke.biz/list?cd=HBC7CEsZqduqmbpb

**Comment by ryutah** [comment]
投票的にはGo。
メンバーの知見的なことを考えると、Go or PHPかなあって所すかね。

<img width="530" alt="image" src="https://user-images.githubusercontent.com/6662577/93663272-9aae1500-faa1-11ea-86f8-5ea3833c9fa7.png">

**Comment by yoshioH** [comment]
とりあえず、Go推し。
ただ、@second10 が何かの知見を得たいという意図があるのであればそれを含めて検討。
9/21に最終決定する。

**Comment by yoshioH** [comment]
GOで決定！！
