### ISSUE TITLE
editorconfig設定を追加する

### ISSUE THREAD

**Issue by ryutah** [dokurin/exhibition#30]
エディタのスタイルがメンバーごとにバラバラだと結構困るので、 [Editor Config](https://editorconfig.org/) スタイルを統一したい

## Todo

- [EditorConfig](https://editorconfig.org/) の設定を追加

---

設定追加したら、みんなのエディタにEditor Configのプラグイン入れたり、CIでスタイルチェックしたりやったほうがいいね。

それはまた別Issueを建てて取り組んでくのがいいかな

僕以外がやってもいいかなと思うので、AssigneesとProjectsはなしでIssue作成しとります。

**Comment by ryutah** [comment]
@yoshioH @itor319 @second10 

ちょっと該当する2系のラベルが無いかも？
こんな感じの、フォーマッタとかLinterとかの開発環境の設定系のことやるためのラベルとして `2:環境設定` とか追加する感じがいいすかね？

**Comment by yoshioH** [comment]
そうね、どのみち `環境設定` は必要になると思うから追加したほうがいいと思う。

**Comment by yoshioH** [comment]
editorconfig設定は @second10 はちょっとやってみてもいいかも？
僕もやってみたいんだけど、手が回らなさそうだから二の足を踏んでます。

**Comment by ryutah** [comment]
とりあえず、僕がばばばーっと設定追加してPR出しちゃう
